// This file is auto-generated by @hey-api/openapi-ts

import type {
  AuthTestTokenResponse,
  ItemsCreateItemResponse,
  ItemsReadItemResponse,
  ItemsReadItemsResponse,
  ItemsUpdateItemResponse,
  PrivateCreateUserResponse,
  UsersCreateUserResponse,
  UsersReadUserByIdResponse,
  UsersReadUserMeResponse,
  UsersReadUsersResponse,
  UsersRegisterUserResponse,
  UsersUpdateUserMeResponse,
  UsersUpdateUserResponse,
} from './types.gen'

const userPublicSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  return data
}

export const authTestTokenResponseTransformer = async (
  data: any,
): Promise<AuthTestTokenResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

const usersPublicSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return userPublicSchemaResponseTransformer(item)
  })
  return data
}

export const usersReadUsersResponseTransformer = async (
  data: any,
): Promise<UsersReadUsersResponse> => {
  data = usersPublicSchemaResponseTransformer(data)
  return data
}

export const usersCreateUserResponseTransformer = async (
  data: any,
): Promise<UsersCreateUserResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

export const usersReadUserMeResponseTransformer = async (
  data: any,
): Promise<UsersReadUserMeResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

export const usersUpdateUserMeResponseTransformer = async (
  data: any,
): Promise<UsersUpdateUserMeResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

export const usersRegisterUserResponseTransformer = async (
  data: any,
): Promise<UsersRegisterUserResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

export const usersReadUserByIdResponseTransformer = async (
  data: any,
): Promise<UsersReadUserByIdResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

export const usersUpdateUserResponseTransformer = async (
  data: any,
): Promise<UsersUpdateUserResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}

const itemPublicSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  return data
}

const itemsPublicSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return itemPublicSchemaResponseTransformer(item)
  })
  return data
}

export const itemsReadItemsResponseTransformer = async (
  data: any,
): Promise<ItemsReadItemsResponse> => {
  data = itemsPublicSchemaResponseTransformer(data)
  return data
}

export const itemsCreateItemResponseTransformer = async (
  data: any,
): Promise<ItemsCreateItemResponse> => {
  data = itemPublicSchemaResponseTransformer(data)
  return data
}

export const itemsReadItemResponseTransformer = async (
  data: any,
): Promise<ItemsReadItemResponse> => {
  data = itemPublicSchemaResponseTransformer(data)
  return data
}

export const itemsUpdateItemResponseTransformer = async (
  data: any,
): Promise<ItemsUpdateItemResponse> => {
  data = itemPublicSchemaResponseTransformer(data)
  return data
}

export const privateCreateUserResponseTransformer = async (
  data: any,
): Promise<PrivateCreateUserResponse> => {
  data = userPublicSchemaResponseTransformer(data)
  return data
}
