// This file is auto-generated by @hey-api/openapi-ts

import type {
  ItemsCreateItemResponse,
  ItemsReadItemResponse,
  ItemsReadItemsResponse,
  ItemsUpdateItemResponse,
} from './types.gen'

const itemPublicSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at)
  data.updated_at = new Date(data.updated_at)
  return data
}

const itemsPublicSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    return itemPublicSchemaResponseTransformer(item)
  })
  return data
}

export const itemsReadItemsResponseTransformer = async (
  data: any,
): Promise<ItemsReadItemsResponse> => {
  data = itemsPublicSchemaResponseTransformer(data)
  return data
}

export const itemsCreateItemResponseTransformer = async (
  data: any,
): Promise<ItemsCreateItemResponse> => {
  data = itemPublicSchemaResponseTransformer(data)
  return data
}

export const itemsReadItemResponseTransformer = async (
  data: any,
): Promise<ItemsReadItemResponse> => {
  data = itemPublicSchemaResponseTransformer(data)
  return data
}

export const itemsUpdateItemResponseTransformer = async (
  data: any,
): Promise<ItemsUpdateItemResponse> => {
  data = itemPublicSchemaResponseTransformer(data)
  return data
}
