/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as Oauth2CallbackRouteImport } from './routes/oauth2/callback'
import { Route as AuthSignupRouteRouteImport } from './routes/_auth/signup/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppItemsRouteRouteImport } from './routes/_app/items/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppItemsItemIdRouteRouteImport } from './routes/_app/items_/$itemId/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const Oauth2CallbackRoute = Oauth2CallbackRouteImport.update({
  id: '/oauth2/callback',
  path: '/oauth2/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppItemsRouteRoute = AppItemsRouteRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppItemsItemIdRouteRoute = AppItemsItemIdRouteRouteImport.update({
  id: '/items_/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AppAdminRouteRoute
  '/items': typeof AppItemsRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/signup': typeof AuthSignupRouteRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
  '/': typeof AppIndexRoute
  '/items/$itemId': typeof AppItemsItemIdRouteRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRouteRoute
  '/items': typeof AppItemsRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/signup': typeof AuthSignupRouteRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
  '/': typeof AppIndexRoute
  '/items/$itemId': typeof AppItemsItemIdRouteRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRouteRoute
  '/_app/items': typeof AppItemsRouteRoute
  '/_app/settings': typeof AppSettingsRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_auth/signup': typeof AuthSignupRouteRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/items_/$itemId': typeof AppItemsItemIdRouteRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/items'
    | '/settings'
    | '/login'
    | '/signup'
    | '/oauth2/callback'
    | '/'
    | '/items/$itemId'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/items'
    | '/settings'
    | '/login'
    | '/signup'
    | '/oauth2/callback'
    | '/'
    | '/items/$itemId'
    | '/dashboard'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/admin'
    | '/_app/items'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/oauth2/callback'
    | '/_app/'
    | '/_app/items_/$itemId'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  Oauth2CallbackRoute: typeof Oauth2CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/oauth2/callback': {
      id: '/oauth2/callback'
      path: '/oauth2/callback'
      fullPath: '/oauth2/callback'
      preLoaderRoute: typeof Oauth2CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/items_/$itemId': {
      id: '/_app/items_/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AppItemsItemIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRoute
  AppItemsRouteRoute: typeof AppItemsRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppItemsItemIdRouteRoute: typeof AppItemsItemIdRouteRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRoute,
  AppItemsRouteRoute: AppItemsRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppIndexRoute: AppIndexRoute,
  AppItemsItemIdRouteRoute: AppItemsItemIdRouteRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthSignupRouteRoute: typeof AuthSignupRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthSignupRouteRoute: AuthSignupRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  Oauth2CallbackRoute: Oauth2CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
